# Transform the data

load("./feedback_catData.RData")


# Create Employee Nos
employees = unique(feedback_catData[,1])
numEmployees = length(employees)
empVec = sapply(1:numEmployees, FUN=function(x) paste(c('E',x),collapse=""))
empSpan = sapply(1:dim(feedback_catData)[1], FUN=function(i) empVec[which(employees == feedback_catData[i,1])])
feedback_catData$Employee <- empSpan

# Create Manager Nos
managers = unique(feedback_catData[,2])
numManagers = length(managers)
manVec = sapply(1:numManagers, FUN=function(x) paste(c('M',x),collapse=""))
manSpan = sapply(1:dim(feedback_catData)[1], FUN=function(i) manVec[which(managers == feedback_catData[i,2])])
feedback_catData$Current.Manager <- manSpan

# Create Flow Ids
flowE = sapply(1:dim(feedback_catData)[1], FUN = function(i) gsub("[[:punct:]]"," ",as.character(feedback_catData[i,3])))
flowE = sapply(flowE,FUN=function(i) tolower(strsplit(as.character(i),split=c(" "))[[1]][1]))
feedback_catData$Emp.Flow.Status <- flowE

flowM = sapply(1:dim(feedback_catData)[1], FUN = function(i) gsub("[[:punct:]]"," ",as.character(feedback_catData[i,4])))
flowM = sapply(flowM,FUN=function(i) tolower(strsplit(as.character(i),split=c(" "))[[1]][1]))
feedback_catData$Mgr.Flow.Status <- flowM

flows = c("arousal","flow","control","unexcited","boredom","apathy","worry","anxiety")
numFlows = length(flows)
flowVec = sapply(1:numFlows, FUN=function(x) x-1)

flowESpan = sapply(1:dim(feedback_catData)[1], FUN=function(i) flowVec[which(flows == feedback_catData[i,3])])
feedback_catData$Emp.Flow.Status <- flowESpan

flowMSpan = sapply(1:dim(feedback_catData)[1], FUN=function(i) flowVec[which(flows == feedback_catData[i,4])])
feedback_catData$Mgr.Flow.Status <- flowMSpan

# Drop Dimention Col
feedback_catData = feedback_catData[,-5]

# Create Factor IDs
factors = unique(feedback_catData[,5])
numFactors = length(factors)
facVec = sapply(1:numFactors, FUN=function(x) paste(c('F',x),collapse=""))
facSpan = sapply(1:dim(feedback_catData)[1], FUN=function(i) facVec[which(factors == feedback_catData[i,5])])
feedback_catData$Behavior <- facSpan

# Create Response IDs for behaviours
responses = c("Demonstrates Independently","Demonstrates with Guidance","Does not Demonstrate","No Opportunity Presented")
numResponses = length(responses)
resVec = c(1,0.5,0.15,0.1)

resESpan = sapply(1:dim(feedback_catData)[1], FUN=function(i) resVec[which(responses == feedback_catData[i,6])])
feedback_catData$Emp.Beh.Rating <- resESpan

resMSpan = sapply(1:dim(feedback_catData)[1], FUN=function(i) resVec[which(responses == feedback_catData[i,7])])
feedback_catData$Mgr.Beh.Rating <- resMSpan

# Assign Easier Colnames to DF
colnames(feedback_catData) = c("Employee","Manager","FlowE","FlowM","Fac","ResE","ResM")


# Function to reshape the data
formattedFeedback_cat = reshape(feedback_catData,idvar="Employee",direction="wide",timevar="Fac",v.names=c("ResE","ResM"))

# Replace NAs generated by "Opportunity not Provided'
formattedFeedback_cat = replace(formattedFeedback_cat,is.na(formattedFeedback_cat),0.1)

save(formattedFeedback_cat,file="formattedFeedback_cat.RData")